export const POSTS = {
    LOAD_POSTS: 'LOAD_POSTS',
    OPEN_POST: 'OPEN_POST',
    ADD_TO_FAVORITE: 'ADD_TO_FAVORITE',
    REMOVE_FROM_FAVORITE: 'REMOVE_FROM_FAVORITE',
    TOGGLE_FAVORITE: 'TOGGLE_FAVORITE'
} as const;
